'use strict';

module.exports = {
'at-rule-no-vendor-prefix': require('stylelint/lib/rules/at-rule-no-vendor-prefix/index.js'),
'media-feature-name-no-vendor-prefix': require('stylelint/lib/rules/media-feature-name-no-vendor-prefix/index.js'),
'property-no-vendor-prefix': require('stylelint/lib/rules/property-no-vendor-prefix/index.js'),
'selector-no-vendor-prefix': require('stylelint/lib/rules/selector-no-vendor-prefix/index.js'),
'value-no-vendor-prefix': require('stylelint/lib/rules/value-no-vendor-prefix/index.js'),
'alpha-value-notation': require('stylelint/lib/rules/alpha-value-notation/index.js'),
'at-rule-empty-line-before': require('stylelint/lib/rules/at-rule-empty-line-before/index.js'),
'color-hex-length': require('stylelint/lib/rules/color-hex-length/index.js'),
'comment-empty-line-before': require('stylelint/lib/rules/comment-empty-line-before/index.js'),
'comment-whitespace-inside': require('stylelint/lib/rules/comment-whitespace-inside/index.js'),
'custom-property-empty-line-before': require('stylelint/lib/rules/custom-property-empty-line-before/index.js'),
'declaration-empty-line-before': require('stylelint/lib/rules/declaration-empty-line-before/index.js'),
'function-calc-no-unspaced-operator': require('stylelint/lib/rules/function-calc-no-unspaced-operator/index.js'),
'function-name-case': require('stylelint/lib/rules/function-name-case/index.js'),
'hue-degree-notation': require('stylelint/lib/rules/hue-degree-notation/index.js'),
'length-zero-no-unit': require('stylelint/lib/rules/length-zero-no-unit/index.js'),
'media-feature-range-operator-space-after': require('stylelint/lib/rules/media-feature-range-operator-space-after/index.js'),
'media-feature-range-operator-space-before': require('stylelint/lib/rules/media-feature-range-operator-space-before/index.js'),
'rule-empty-line-before': require('stylelint/lib/rules/rule-empty-line-before/index.js'),
'selector-pseudo-element-colon-notation': require('stylelint/lib/rules/selector-pseudo-element-colon-notation/index.js'),
'selector-type-case': require('stylelint/lib/rules/selector-type-case/index.js'),
'value-keyword-case': require('stylelint/lib/rules/value-keyword-case/index.js'),
};